server:
  port: 8080
spring:
  datasource:
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always