server:
  port: 9090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
    level:
      org.hibernate:
        type: debug
        sql: debug
      org.springframework: debug

api :
  url : "https://kr.api.riotgames.com"

path :
  riotGames:
    api :
      key: "RGAPI-6ed51fa1-0ed9-48a5-991a-ee66b92d3339"


